name: Android Build

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        default: default
        type: string
      ref:
        required: false
        type: string 
      NVMRC:
        required: true
        type: string
      MAP_IMPL:
        description: "The map implementation to use (mapbox,mapbox11)"
        default: mapbox
        required: false
        type: string
      NEW_ARCH:
        description: "If build with new architecture or not"
        default: false
        required: false
        type: boolean
    secrets:
      MAPBOX_ACCESS_TOKEN:
        required: true
      ENV_MAPBOX_ACCESS_TOKEN:
        required: false